### ISSUE TITLE
Customer cannot close his tickets

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#39]
Hi Steven,
It would be helpful if a button is available for customer  (non employee) to close his tickets.
i.e. Adding a comment and clicking Close instead of Submit.
Regards, Nabeel.

**Comment by SythilTech** [comment]
Yea should really finish that feature, will work it into the next version.

**Comment by hindsa-nabeel** [comment]
Thanks Steven,
The last thing I would want is to sound patronizing. After all, we should acknowledge the favour as you are providing this development to the community for free.

**Comment by SythilTech** [comment]
Hello,

I have introduced this feature in version 1.3.7, the customer can close the ticket under the my tickets link.

**Comment by hindsa-nabeel** [comment]
Thanks Steven,
I have tested the button and it works.
Best regards, Nabeel.
