### ISSUE TITLE
Support Tickets list

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#41]
Hi Seteven,
When a support executive clicks on Customer Support, he gets a list of tickets in the Q, it would be useful if the field "Owner" or "Processor" to indicate who is working on the ticket currently.

Or Owner may indicate the person sending the ticket (instead of Person name) and Processor indicating the Support Executive working on it.

It would be great if this list is a customisable report, such as the painter in SAP. i.e. one can add or remove fields within that report. 

Regards, Nabeel.

**Comment by SythilTech** [comment]
Ok I will consider adding the user_id field to the tree view I was also planning to introduce a locking feature for tickets not assigned to a user as a way of saying someone is already in the process of answering this ticket.
