### ISSUE TITLE
ticket is closed

### ISSUE THREAD

**Issue by jjlopezg** [SythilTech/Odoo#42]
how do you see that when a ticket is closed, that comments can no longer be sent and the button can not be sent?

**Comment by SythilTech** [comment]
The state of the ticket should change to 'Staff Closed' and a closed comment / time will appear in the ticket.

It is still possible for staff / customers to re-open and reply to ticket if they feel it was pre-maturely closed

**Comment by jjlopezg** [comment]
Thank you
