### ISSUE TITLE
Logged User (Odoo 12) cannot create support message

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#51]
A logged-in Support client does not have access to a menu to create a support ticket. While a non-logged user may create a ticket (after configuring the support interface).

**Comment by hindsa-nabeel** [comment]
I found the solution, go to "My Website" all is there..

**Comment by hindsa-nabeel** [comment]
Found the solution, click on "Go to Website", Support menu is there..

However, when I raise a ticket, I get:
**500: Internal Server Error**

**Comment by SythilTech** [comment]
Hello,

Sorry I was not able to reproduce this issue of support client users not being able to submit support tickets via the website interface.

If you could please provide steps to reproduce this issue as well as the information about the 500 internal server error from your Odoo server log that would help.

P.S. You can send the error log to my email steven@sythiltech.com.au as sometimes the logs can contain sensitive information.

**Comment by hindsa-nabeel** [comment]
Hi Steven,
If I create a ticket through Customer Support --> Support Tickets --> Create. All goes fine and the ticket is created. But this is usually for members of support team.

However, If I Click on Website --> Go to Website --> Support --> Submit a ticket. I get most of the fields correctly filled-in, I just add a subject and some description, then I click on submit ticket to get:

Error message:
Expected singleton: res.users(8, 10, 9)

**Comment by SythilTech** [comment]
Thank you for bringing this to my attention, I have released version 1.0.1 to address this issue.

You will need to restart your Odoo instance after replacing the old version for the code changes to take effect.

**Comment by hindsa-nabeel** [comment]
Thanks Steven,
It works now..
And thank you for porting the analytics to 12 as well.
