### ISSUE TITLE
[html_form_builder] many2one dropbox ignores field's domain parameter

### ISSUE THREAD

**Issue by jbofill** [SythilTech/Odoo#52]
When a many2one dropbox selection is added, all registers from de field are selectable, ignoring possible domain parameter set in field definition.

I think you could solve this adding some lines of code so only the records in the fields domain are entered in the selection list when a domain is specified.

controllers/main.py _generate_html_dropbox function: 

```
            if request.env[field.field_id.model].fields_get()[field.field_id.name]['domain']:
                selection_list = request.env[field.field_id.relation].search(
                    request.env[field.field_id.model].fields_get()[field.field_id.name]['domain'])
            else:
                selection_list = request.env[field.field_id.relation].search([])

```

models/html_from.py _generate_html_dropbox:

```
            if request.env[fe.field_id.model].fields_get()[fe.field_id.name]['domain']:
                selection_list = request.env[fe.field_id.relation].search(
                    request.env[fe.field_id.model].fields_get()[fe.field_id.name]['domain'])
            else:
                selection_list = request.env[fe.field_id.relation].search([])

```

**Comment by SythilTech** [comment]
Thank you for the suggestion.

I have released version 1.0.12 for Odoo 11 which now filters which records are displayed in the dropbox (many2one) based on the domain field when it first generates the form.

This applies both to external embed forms and forms generated via the snippets, it however does not take into consideration any domains placed inside back-end views, only those assigned to the field.

**Comment by jbofill** [comment]
Generating the code I get de following error:

```
File "html_form_builder/models/html_form.py", line 62, in generate_form
    html_output += action(fe)

File "html_form_builder/models/html_form.py", line 169, in _generate_html_dropbox
    if field.field_id.domain:
NameError: name 'field' is not defined
```

**Comment by jbofill** [comment]
In any case, `fe.field_id.domain` doesn't return the field's domain.
I don't know a simpler way to obtain it than
```request.env[fe.field_id.model].fields_get()[fe.field_id.name]['domain']```

**Comment by SythilTech** [comment]
Ah sorry that code change was servery under tested. I have released version 1.0.13, this should take into consideration fields created by modules with domains rather then only fields added via the Odoo UI.

**Comment by jbofill** [comment]
Getting this error:

```
  File "html_form_builder/controllers/main.py", line 412, in load_form
    form_string += action(form_field)
  File "html_form_builder/controllers/main.py", line 377, in _generate_html_dropbox
    selection_list = request.env[field.field_id.relation].search(ast.literal_eval(field_domain))
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: [('actor_type', '=', 'highschool')]
```
Passing field_domain as a string solves the issue

```
selection_list = request.env[field.field_id.relation].search(ast.literal_eval(str(field_domain)))
```

**Comment by SythilTech** [comment]
Thank you for bringing this to my attention, I have passed the field_domain as a string to prevent this issue

**Comment by jbofill** [comment]
Thank you!
