### ISSUE TITLE
Downloading SythilTech / Odoo 10 in Custom Addons makes static contents "not found"

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#55]
Hello Steven,
I was experimenting with Odoo 10 over Centos 7.6 in the past few days when I noticed that images and icons disappear from odoo web interface after adding a custom addons location to the path in odoo.conf, like this (addons_path = /usr/lib/python2.7/site-packages/odoo/addons, /usr/lib/python2.7/site-packages/odoo/custom-addons) and downloading SythilTech/Odoo branch 10.0.

Initially I thought it was the new Centos playing tricks, then after few test installations over other OSes and with the process of elimination, I found it was the following items being the root cause of the problem:
1- migration_odbc_import
2- sythil_saas_server_domain_filter
3- voip_sip_webrtc_transcription
4- voip_sip_webrtc_xmpp

If the above items are removed from the "custom-addons" folder and odoo 10 is restarted, all is back to normal. It may be permissions or naming issue, you would know better, but I am sure you will be able to fix it or advice on how to go about it.

Thanks in advance.

**Comment by SythilTech** [comment]
Hello, Sorry for the delay in response, been away during new years and currently catching up.

All 4 modules have special requirements that need to be meet before they can be placed inside your addon folder or successfully installed

1- migration_odbc_import
requires pyodbc Python library installed.

2- sythil_saas_server_domain_filter
This requires editing a core file specifically one that handles database filtering based on sub/domain.

3- voip_sip_webrtc_transcription
requires the speech_recognition software installed.

4- voip_sip_webrtc_xmpp
requires sleekxmpp Python library installed.

for full details please see the static/description/index.html file of each module, exact installation instructions will vary on OS

**Comment by hindsa-nabeel** [comment]
Thanks Steven, 
It is great to know that there are help manuals in static/description/index.html. I will have to learn to access them while working on the system.
