### ISSUE TITLE
Website support - problem upgrading to 1.6.0 in v10

### ISSUE THREAD

**Issue by tuporaqui** [SythilTech/Odoo#56]
Hi, I tried to upgrade this module from version 1.5.14, in odoo version 10.

This is the error I get:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 641, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 683, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 941, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 895, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 883, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 528, in button_immediate_upgrade
>     return self._button_immediate_function(type(self).button_upgrade)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 335, in load_modules
>     force, status, report, loaded_modules, update_module)
>   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 136, in load_module_graph
>     registry.init_models(cr, model_names, {'module': package.name})
>   File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 317, in init_models
>     model._auto_init()
>   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 2511, in _auto_init
>     self._init_column(name)
>   File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 2281, in _init_column
>     value = field.default(self)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/website_support/models/website_support_ticket.py", line 54, in _default_approval_id
>     return self.env['ir.model.data'].get_object('website_support', 'no_approval_required')
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1131, in get_object
>     return self.xmlid_to_object("%s.%s" % (module, xml_id), raise_if_not_found=True)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1092, in xmlid_to_object
>     t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
>     return self.xmlid_lookup(xmlid)[1:3]
>   File "<string>", line 2, in xmlid_lookup
>   File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
>     value = d[key] = self.method(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
>     raise ValueError('External ID not found in the system: %s' % xmlid)
> ValueError: External ID not found in the system: website_support.no_approval_required
>

**Comment by SythilTech** [comment]
Thank you for bringing this issue to my attention.

I have released version 1.6.1 for Odoo 10 to address this issue with people upgrading from older versions.

**Comment by tuporaqui** [comment]
Update ok with this version, thank you very much!
