### ISSUE TITLE
link to projects

### ISSUE THREAD

**Issue by markfoodyburton** [SythilTech/Odoo#62]
Hi 

Would it be possible to use 'project tasks' instead of 'support tickets' as the underlying data item? Then you would get all the kanboard, viewing etc 'for free', and you would be able to see your support tickets with the rest of your projects. Of course you could set things up to use one or more specific 'support' projects, or you could choose to assign issues directly to other projects. It would seem to be a more flexible approach, and could simplify this module? (It would also facilitate moving a troublesome support ticket into an engineering project, without having to re-create the issue!)

Cheers
Mark.

**Comment by SythilTech** [comment]
Hello Mark,

Such a thing would be quite time consuming to change at this point in the modules development.

You can create a link to projects / task using the website_support_analytic_timesheets module though as it is designed to let you see time spent on tasks and tickets side by side.

Other then that using dashboards might helps centralise the management of both projects and tasks.

Regards
Steven

**Comment by markfoodyburton** [comment]
Thanks for this, I had done this, and FWIT, in the end I think it's nice to keep support tickets separately from related project tasks - with a link between them, which is easy to setup.
