### ISSUE TITLE
Attachments on comments

### ISSUE THREAD

**Issue by markfoodyburton** [SythilTech/Odoo#64]
It would be great if you could add attachments when you submit  comments (e.g. additional log files etc). Looks like this would need to be supported in the controller...

**Comment by SythilTech** [comment]
Hi, I have added this feature to version 1.5.12 in Odoo 11

**Comment by markfoodyburton** [comment]
Oh, great ! - is it possible to port it to Odoo 12?

**Comment by SythilTech** [comment]
Sure it has been ported to Odoo 12 as version 1.0.6

**Comment by markfoodyburton** [comment]
THANKS for this !
