### ISSUE TITLE
Support Comment Field Missing

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#66]
Hi Steven,
The Support Comment entry field seems to have disappeared in the latest Website-Support releases, it is no longer possible to enter internal comments. 
It would be great if you could fix this issue. Thanks in advance,
Nabeel.

**Comment by SythilTech** [comment]
Hello,

Sorry I am not clear the log a note button is still there, can you please provide additional details

Regards
Steven

**Comment by hindsa-nabeel** [comment]
I have attached a snapshot of the missing text entry field (internal Comments that cannot be seen by customer). I have version 1.5.15 installed (5 Mar 19).

Also, when you change the ticket processor (for reasons of specialisation, competence or escalation), the new processor does not get a message in his inbox. For example, the attached ticket has been assigned to Sup-1 by Man-1 (the manager), but when Sup-1 logs into odoo, he is congratulated on his inbox being clean

However, the Administrator does get inbox alerts that tickets/messages have arrived through email (but not tickets that have been internally assigned to him). It looks like a security/authorisation configuration issue, can you advise on how to configure this such that processors receive alerts that a ticket has been assigned to them? 

![ws-test](https://user-images.githubusercontent.com/32294655/53858065-82b29580-3fd0-11e9-96b8-b4a2a6fb3f32.jpg)

**Comment by SythilTech** [comment]
Support comment field is the comment made by the customer after the survey is sent out, the only change is the field was changed to read-only to prevent staff alteration.

log note should track which user made the note and should not be visible to the customer (if it is please provide where)

When a user is assigned it should send out the "A Support Ticket has been assigned to you" email template, this uses the company email as the from address so they will need that setup as an outgoing email server.

You can check for any failed emails under settings->technical->email->emails menu while in debug mode.

**Comment by hindsa-nabeel** [comment]
Thank you for your reply, it seems I have misunderstood the purpose of this field.
Then I think a field for internal comments that only the personnel processing the ticket can edit/view is needed as the various business and technical layers of the organisation confidentially communicate concerning the issue.

I actually have the Outgoing and Incoming Servers already set and they successfully communicate between customers email and the odoo system, but for some reason, when you click on the conversations icon of the logged support employees, you find this error:

Odoo Server Error - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: mail.message, Operation: read)

Regards, Nabeel.
